# Environment variables
env:
  system:
    __ZZ_PROFILE__: 1
  user:
    any:
      LANG: zh_CN.UTF-8
    cli:
      # N/A
    gui:
      GTK_IM_MODULE: ibus
      QT_IM_MODULE: ibus
      XMODIFIERS: @im=ibus
